---

- name: add domain controller private IP as DNS server
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "{{ dns_servers | default([]) }}"

- name: add windows server to the domain
  win_domain_membership:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_admin_user: "{{ domain_admin_username }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: join_domain

- name: reboot server if required
  win_reboot:
  when: join_domain.reboot_required
