- name: remove computer object to the domain
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: add a powershell module
      win_psmodule:
        name: xActiveDirectory
        state: present

    - debug:
        var: miq_provision_options

    - debug:
        msg: "{{ miq_provision_options[':vm_name'] }}"

    - name: remove computer object
      win_dsc:
        resource_name: xADComputer
        ComputerName: "{{ computer_name }}"
        Path: '{{ join_ou_path }}'
        Ensure: Absent
      when:
      - computer_name is defined
      - join_ou_path is defined