- name: remove computer objects
  hosts: all
  gather_facts: no
  serial: 1
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: ad-computer-registration
      role_action: deregister
      computer_name: "{{ ansible_hostname | default('guest.hostname') }}"
      delegate_to: "{{ windows_ad_server_ip }}"

- name: remove cluster object
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: ad-computer-registration
      role_action: deregister
      computer_name: "{{ cluster_name }}"
      delegate_to: "{{ windows_ad_server_ip }}"
      when: cluster_name is defined