- name: remove computer objects
  hosts: all
  gather_facts: no
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: ad-computer-registration
      role_action: deregister
      computer_name: "{{ ansible_host }}"
      delegate_to: "{{ windows_ad_server_ip }}"