- name: join server to the domain
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: ad-computer-registration
      role_action: deregister
      computer_name: "{{ inventory_hostname }}"
      delegate_to: "{{ dns_servers | default(omit) }}"
      become: yes
      become_user: "{{ domain_admin_username }}@{{ dns_domain_name }}"
      become_password: "{{ domain_admin_password }}"
    - domain