- name: Create a db on MSSQL
  hosts: all
  gather_facts: no

  tasks:
    - name: Create a db
      mssql_db:
        login_host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
        name: redhatdemo
        state: present
      delegate_to: 127.0.0.1