- name: Create a db on MSSQL
  hosts: all
  gather_facts: no
  vars:
    login_user: sqladmin
    login_password: Password!1
  tasks:
  - name: Create a db
    mssql_db:
      login_host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
      login_user: "{{ login_user | default(omit) }}"
      login_password: "{{ login_password | default(omit) }}"
      login_port: "{{ login_port | default(omit) }}"
      name: redhatdemo
      state: present
    delegate_to: 127.0.0.1