- name: Create a db on MSSQL
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm

  tasks:
  - name: Create a db
    mssql_db:
      name: chevron
      state: present
    delegate_to: 127.0.0.1