- name: windows change tcpip parameters
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: change tcpip parameter
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: EnablePMTUDiscovery
        data: 0
        type: dword

    - name: get interfaces
      win_reg_stat:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\
      register: interface_ids

    - debug:
        var: interface_ids.value

#    - name: set mtu size
#      win_regedit:
#        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\
#        name: MTU
#        data: 0
#        type: dword