- name: Install Windows Updates
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
  - role: deekayen.win_updates
    win_updates_reboot: true
    win_updates_category_names:
      - "CriticalUpdates"
      - "SecurityUpdates"