- name: Deploy Windows Servers
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars_files:
    - win-nodes-vmware.yml
    
  roles:
  #- deploy
  - role: ansible-role-vmware
    ansible_port: 5986