- name: Delete Windows Instance on Azure
  hosts: localhost
  gather_facts: False
  connection: local
  become: no
  vars:
    ansible_port: 5986
    windows: yes
  tasks:
    - name: Delete a resource group
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: southcentralus
        state: absent
        force: yes