- name: Deploy Windows Instance on Azure
  hosts: localhost
  gather_facts: False
  connection: local
  become: no
  vars:
    ansible_port: 5986
    windows: yes
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: southcentralus
        tags:
          testing: testing
          delete: never
      ignore_errors: yes

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: myResourceGroup
        name: myVnet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: myResourceGroup
        name: mySubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: myVnet

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: myResourceGroup
        allocation_method: Static
        name: myPublicIP

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: myResourceGroup
        name: myNetworkSecurityGroup
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create virtual network inteface card
      azure_rm_networkinterface:
        resource_group: myResourceGroup
        name: myNIC
        virtual_network: myVnet
        subnet: mySubnet
        public_ip_name: myPublicIP
        security_group: myNetworkSecurityGroup

    - name: Create Windows VM
      azure_rm_virtualmachine:
        resource_group: myResourceGroup
        name: AnsibleWin2
        vm_size: Standard_A1
        public_ip_allocation_method: Dynamic
        open_ports:
          - 3389
          - 5985
          - 5986
        os_type: Windows
        admin_username: ansible
        admin_password: "{{ ansible_password }}"
        image:
          sku: 2012-R2-Datacenter
          publisher: MicrosoftWindowsServer
          version: latest
          offer: WindowsServer
      register: azure

    - name: Create VM Extension 0
      azure_rm_virtualmachine_extension:
        name: myvmextension0
        resource_group: myResourceGroup
        virtual_machine_name: AnsibleWin2
        publisher: Microsoft.Azure.Extensions
        virtual_machine_extension_type: CustomScript
        type_handler_version: 2.0
        settings: '{"commandToExecute": "hostname"}'
        auto_upgrade_minor_version: true

    - name: Create VM Extension
      azure_rm_virtualmachine_extension:
        name: myvmextension
        resource_group: myResourceGroup
        virtual_machine_name: AnsibleWin2
        publisher: Microsoft.Azure.Extensions
        virtual_machine_extension_type: CustomScript
        type_handler_version: 2.0
        settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell.exe -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP"}'
        auto_upgrade_minor_version: true

    - name: Debug variable
      debug:
        msg: "ip address: {{ azure.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"

    - name: Waiting for server to come online
      wait_for:
        host: "{{ azure.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
        port: "{{ ansible_port }}"
        timeout: 600
