---
- debug:
    msg: "hostname is {{ hostname }}"

- debug:
    msg: "ansible_hostname is {{ ansible_hostname }}"

- name: change hostname
  win_shell: Rename-Computer -NewName {{ hostname }}
  when: hostname|lower != ansible_hostname|lower
  register: change_hostname

- name: windows reboot
  win_reboot:
  when: change_hostname | changed
