---

- name: Create an incident
  snow_record:
    state: present
    table: cmdb_ci_linux_server
    username: "{{ sn_username }}"
    password: "{{ sn_password }}"
    instance: "{{ sn_instance }}"
    data:
      os: redhat
  delegate_to: localhost
  vars:
    ansible_connection: local
  register: new_host

- debug:
    var: new_host
