---

- name: Create an incident
  snow_record:
    state: present
    table: cmdb_ci_win_server
    username: "{{ sn_username }}"
    password: "{{ sn_password }}"
    instance: "{{ sn_instance }}"
    data:
      name: "{{ inventory_hostname }}"
      host_name: "{{ ansible_hostname | lower }}"
      ip_address: "{{ ansible_host }}"
      mac_address: "{{ ansible_interfaces[0].macaddress }}"
      os: "{{ ansible_distribution }}"
  delegate_to: localhost
  vars:
    ansible_connection: local
  register: new_host

- debug:
    var: new_host
