- name: stop iis service
  win_dsc:
    resource_name: service
    name: W3Svc
    state: stopped
    startuptype: auto

- name: start iis service
  win_dsc:
    resource_name: service
    name: W3Svc
    state: Running
    startuptype: auto