# Install SQL 2016

- name: set up sqladmin user
  win_user:
    name: sqladmin
    password: Password1!
    password_never_expires: True
    state: present
    groups:
      - Administrators

- name: install .Net
  win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: True
    include_management_tools: True
  with_items:
    - NET-Framework-Core
    - NET-Framework-Features

- name: create directory structure
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - C:\Backup
    - C:\Databases
    - C:\UserDatabases

- name: check ISO file
  win_stat:
    path: "{{ iso_path }}"
  register: iso_file
  when: (":" in iso_path)

- name: download ISO file
  win_get_url:
    dest: "{{ iso_path }}"
    url: "http://care.dlservice.microsoft.com/dl/download/F/E/9/FE9397FA-BFAB-4ADD-8B97-91234BC774B2/SQLServer2016-x64-ENU.iso"
  when: (":" in iso_path) and (not iso_file.stat.exists)

- name: mount iso
  win_disk_image:
    image_path: "{{ iso_path }}"
    state: present
  register: disk_image_out

- import_tasks: "{{ install_with }}.yml"
  when: ansible_version.full | version_compare('2.4', '>=')

- include: "{{ install_with }}.yml"
  when: ansible_version.full | version_compare('2.4', '<')

- name: unmount iso
  win_disk_image:
    image_path: "{{ iso_path }}"
    state: absent

- name: copy script file
  win_copy:
    src: enableSQLTCP.ps1
    dest: c:\enableSQLTCP.ps1

- name: enable tcp on SQL server instance
  win_shell: c:\enableSQLTCP.ps1

- name: restart SQL Server instance
  win_service:
    name: MSSQLSERVER
    state: restarted
