# Install SQL 2016

- name: Set up sqladmin user
  win_user:
    name: sqladmin
    password: Password1!
    password_never_expires: True
    state: present
    groups:
      - Administrators

- name: Install .Net
  win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: True
    include_management_tools: True
  with_items:
    - NET-Framework-Core
    - NET-Framework-Features

- name: Create directory structure
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - C:\Backup
    - C:\Databases
    - C:\UserDatabases

#- name: mount iso
#  win_disk_image:
#    image_path: \\192.168.1.103\iso\SQLServer2016SP1-FullSlipstream-x64-ENU-DEV.iso
#    state: present
#  register: disk_image_out

- name: Check ISO file
  win_stat:
    path: "{{ ansible_env.TEMP }}\\sql2016.iso"
  register: iso_file

- name: Download ISO file
  win_get_url:
    dest: "{{ ansible_env.TEMP }}\\sql2016.iso"
    url: "http://care.dlservice.microsoft.com/dl/download/F/E/9/FE9397FA-BFAB-4ADD-8B97-91234BC774B2/SQLServer2016-x64-ENU.iso"
  when: not iso_file.stat.exists

- name: mount iso
  win_disk_image:
    image_path: "{{ ansible_env.TEMP }}\\sql2016.iso"
    state: present
  register: disk_image_out

- name: Get execution policy
  win_shell: |
    Get-ExecutionPolicy
  register: execution_policy

- name: debug execution policy
  debug:
    msg: "{{ execution_policy }}"

- name: Enable CredSSP
  win_shell: powershell –ExecutionPolicy Bypass -File C:\ConfigureRemotingForAnsible2.ps1 -EnableCredSSP
  args:
    executable: cmd

- name: Create SQL 2016 Install Script
  win_template:
    src: templates/installSQL2016.ps1
    dest: C:\installSQL2016.ps1

- name: Unblock script
  win_shell: |
    Unblock-File C:\installSQL2016.ps1

- name: Install SQL 2016
  win_shell: c:\installSQL2016.ps1
  args:
    chdir: c:\
    creates: c:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER

# using win_package
#- name: Install SQL 2016
#  win_package:
#    path: '{{ disk_image_out.mount_path }}\setup.exe'
#    product_id: '{0AE831BC-F2A8-4DE2-8FBF-68B220611A7F}'
#    arguments: '/Q /ACTION=Install /IACCEPTSQLSERVERLICENSETERMS /ENU /UPDATEENABLED=false /FEATURES=SQLENGINE /INSTANCENAME=MSSQLSERVER /SECURITYMODE=SQL /SAPWD=Password1! /AGTSVCSTARTUPTYPE=automatic /BROWSERSVCSTARTUPTYPE=automatic /SQLSYSADMINACCOUNTS=sqladmin /SQLBACKUPDIR=C:\Backup /SQLUSERDBDIR=C:\Databases /SQLUSERDBLOGDIR=C:\UserDatabases'
#    state: present
#    expected_return_code: [0,3010]

- name: unmount iso
  win_disk_image:
    image_path: "{{ ansible_env.TEMP }}\\sql2016.iso"
    state: absent


