# Install SQL 2016

- name: Set up sqladmin user
  win_user:
    name: sqladmin
    password: Password1!
    password_never_expires: True
    state: present
    groups:
      - Administrators

- name: Install .Net
  win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: True
    include_management_tools: True
  with_items:
    - NET-Framework-Core
    - NET-Framework-Features
    #- NET-Framework-45-Features
    #- NET-Framework-45-Core
    #- NET-Framework-45-ASPNET

- name: Create directory structure
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - C:\Backup
    - C:\Databases
    - C:\UserDatabases

- name: Check ISO file
  win_stat:
    path: "{{ iso_path }}"
  register: iso_file
  when: ("{{ '\\' }}" not in iso_path)

- name: Download ISO file
  win_get_url:
    dest: "{{ iso_path }}"
    url: "http://care.dlservice.microsoft.com/dl/download/F/E/9/FE9397FA-BFAB-4ADD-8B97-91234BC774B2/SQLServer2016-x64-ENU.iso"
  when: ("{{ '\\' }}" not in iso_path) and (not iso_file.stat.exists)

- name: mount iso
  win_disk_image:
    image_path: "{{ iso_path }}"
    state: present
  register: disk_image_out

- name: Create SQL 2016 Install Script
  win_template:
    src: templates/installSQL2016.bat
    dest: C:\installSQL2016.bat

#- name: Install SQL 2016
#  win_shell: c:\installSQL2016.bat
#  args:
#    executable: cmd
#    chdir: c:\
#    creates: c:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER

- name: Download PsTools
  win_get_url:
    dest: "{{ ansible_env.TEMP }}\\pstools.zip"
    url: "https://download.sysinternals.com/files/PSTools.zip"

- name: Extract PSTools
  win_unzip:
    src: "{{ ansible_env.TEMP }}\\pstools.zip"
    dest: "{{ ansible_env.TEMP }}\\pstools"
    rm: true

- name: Install SQL 2016
  win_psexec:
   command: c:\installSQL2016.bat
   priority: high
   executable: "{{ ansible_env.TEMP }}\\pstools\\psexec.exe"

# using win_package
#- name: Install SQL 2016
#  win_package:
#    path: '{{ disk_image_out.mount_path }}\setup.exe'
#    product_id: '{0AE831BC-F2A8-4DE2-8FBF-68B220611A7F}'
#    arguments: '/Q /ACTION=Install /IACCEPTSQLSERVERLICENSETERMS /ENU /UPDATEENABLED=false /FEATURES=SQLENGINE /INSTANCENAME=MSSQLSERVER /SECURITYMODE=SQL /SAPWD=Password1! /AGTSVCSTARTUPTYPE=automatic /BROWSERSVCSTARTUPTYPE=automatic /SQLSYSADMINACCOUNTS=sqladmin /SQLBACKUPDIR=C:\Backup /SQLUSERDBDIR=C:\Databases /SQLUSERDBLOGDIR=C:\UserDatabases'
#    state: present
#    expected_return_code: [0,3010]

- name: unmount iso
  win_disk_image:
    image_path: "{{ iso_path }}"
    state: absent