---
- name: Download PsTools
  win_get_url:
    dest: "{{ ansible_env.TEMP }}\\pstools.zip"
    url: "https://download.sysinternals.com/files/PSTools.zip"

- name: Extract PSTools
  win_unzip:
    src: "{{ ansible_env.TEMP }}\\pstools.zip"
    dest: "{{ ansible_env.TEMP }}\\pstools"
    rm: true

- name: Install SQL 2016
  win_psexec:
    command: "{{ disk_image_out.mount_path }}setup.exe /Q /ACTION=Install /IACCEPTSQLSERVERLICENSETERMS /ENU /UPDATEENABLED=false /FEATURES=SQLENGINE /INSTANCENAME=MSSQLSERVER /SECURITYMODE=SQL /SAPWD=Password1! /AGTSVCSTARTUPTYPE=automatic /BROWSERSVCSTARTUPTYPE=automatic /SQLSYSADMINACCOUNTS=sqladmin /SQLBACKUPDIR=C:\Backup /SQLUSERDBDIR=C:\Databases /SQLUSERDBLOGDIR=C:\\UserDatabases"
    priority: high
    executable: "{{ ansible_env.TEMP }}\\pstools\\PsExec.exe"