---
- name: install SQL 2016
  win_dsc:
    resource_name: Package
    Path: '{{ disk_image_out.mount_path }}setup.exe'
    ProductId: '{1ca29225-1d60-4199-b502-eed97d1eafb5}'
    Arguments: >
      /Q
      /ACTION=Install
      /IACCEPTSQLSERVERLICENSETERMS
      /ENU
      /UPDATEENABLED=false
      /FEATURES=SQLENGINE,Conn
      /INSTANCENAME=MSSQLSERVER
      /SECURITYMODE=SQL
      /SAPWD={{ mssql_password }}
      /AGTSVCSTARTUPTYPE=automatic
      /BROWSERSVCSTARTUPTYPE=automatic
      /SQLSYSADMINACCOUNTS={{ mssql_username }}
      /SQLBACKUPDIR=C:\Backup
      /SQLUSERDBDIR=C:\Databases
      /SQLUSERDBLOGDIR=C:\UserDatabases